---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/signup":
    post:
      summary: User signup
      tags:
      - Users
      parameters:
      - name: name
        in: path        
        required: true
        schema:
          type: string
      - name: email
        in: path        
        required: true
        schema:
          type: email
      - name: password
        in: path        
        required: true
        schema:
          type: password
      
      responses:
        '201':
          description: Account created
        '422':
          description: Invalid credentials

  "/auth/login":
    post:
      summary: User login
      tags:
      - Users
      parameters: 
      - name: email
        in: path        
        required: true
        schema:
          type: email
      - name: password
        in: path        
        required: true
        schema:
          type: password
      responses:
        '201':
          description: auth_token = {token}
        '422':
          description: Invalid credentials
  "/auth/logout":
    get:
      summary: User logout
      tags:
      - Users
      parameters: []
      responses:
        '201':
          description: Successful logout 
        '422':
          description: Invalid request

  "/todos":
    get:
      summary: List all todos and todo items
      tags:
      - Todos
      parameters: []
      responses:
        '404':
          description: No Todos or Todos items found
    post:
      summary: Create a new todo
      tags:
      - Todos
      parameters:
      - name: title
        in: path
        required: true
        schema:
          type: string
      - name: create_by
        in: path
        required: true
        schema:
          type: string
      responses:
        '201':
          description: Todo created
  "/todos/{id}":
    get:
      summary: Get a todo
      tags:
      - Todos
      parameters: []
      responses:
        '404':
          description: Todo not found
    put:
      summary: Update a todo
      tags:
      - Todos
      parameters: []
      responses:
        '200':
          description: Todo update
    delete:
      summary: Delete a todo and its items
      tags:
      - Todos
      parameters: []
      responses:
        '200':
          description: Todo deleted
  "/todos/{id}/items/{iid}":
    get:
      summary: Get a todo item
      tags:
      - Todos
      parameters: []
      responses:
        '200':
          description: Todo item exists
        '404':
          description: Todo item does not exists
    put:
      summary: Update a todo item
      tags:
      - Todos
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '204':
          description: Item exists
        '404':
          description: Item does not exists
    delete:
      summary: Delete a todo item
      tags:
      - Todos
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Todo item deleted
  "/todos/{id}/items":
    post:
      summary: Create a new todo item
      tags:
      - Todos
      parameters:
      - name: name
        in: path
        required: true
        schema:
          type: string
      - name: done
        in: path
        required: true
        schema:
          type: boolean
      responses:
        '201':
          description: request attributes are valid
        '422':
          description: invalid request





servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
